port: :3000

database:
  user: postgres
  password: 2048
  port: 5432
  host: localhost
  dbname: itegodb
  sslmode: disable

email:
  from: bogdan_bogdanov.1@mail.ru
  to: giraffeonelove@gmail.com
  host: smtp.mail.ru
  port: 587
  password: 2TQEU8Gh0MX9viHFDufY

cors:
  addres: http://localhost:8081
  # servaddres:
